# Cleanup stale incarnations in all environments
default: &default
  cleanup_stale_incarnations:
    class: CleanupStaleIncarnationsJob
    queue: maintenance
    schedule: every 10 minutes
    description: "End incarnations that have been active too long or have no recent activity"

development:
  <<: *default

production:
  <<: *default
  # Add production-specific jobs here
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
