# Solid Queue configuration for Rails 8
# https://github.com/basecamp/solid_queue

# Default configuration for all environments
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance:
        enabled: true
        interval: 300 # 5 minutes
  workers:
    - queues: "*"
      threads: 5
      processes: 1
      polling_interval: 0.1
      
development:
  <<: *default
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 0.1

test:
  <<: *default
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 0.1

production:
  <<: *default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance:
        enabled: true
        interval: 300
  workers:
    - queues: [default, maintenance]
      threads: 10
      processes: 2
      polling_interval: 0.1